### ISSUE TITLE
Reading a json map<string, string> throws error

### ISSUE THREAD

**Issue by prismofeverything** [trueaccord/ScalaPB#118]
I have a schema that includes a line

    map<string, string> info = 9;

This is converted into JSON object:

    line = """{"info": { "transcriptStatus": "NP_001150", "transcriptSource": "p.L201L", .... }}"""

But when I try to read it:

    val vce = JsonFormat.fromJsonString[sample.VariantCallEffect](line)

I get the following error: 

    com.trueaccord.scalapb.json.JsonFormatException: Expected an array for repeated field info of VariantCallEffect
      at com.trueaccord.scalapb.json.JsonFormat$.com$trueaccord$scalapb$json$JsonFormat$$parseValue$1(JsonFormat.scala:44)
      at com.trueaccord.scalapb.json.JsonFormat$$anonfun$2$$anonfun$apply$1.apply(JsonFormat.scala:89)
      at com.trueaccord.scalapb.json.JsonFormat$$anonfun$2$$anonfun$apply$1.apply(JsonFormat.scala:88)
      at scala.Option.map(Option.scala:146)
      at com.trueaccord.scalapb.json.JsonFormat$$anonfun$2.apply(JsonFormat.scala:88)
      at com.trueaccord.scalapb.json.JsonFormat$$anonfun$2.apply(JsonFormat.scala:87)
      at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
      at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
      at scala.collection.Iterator$class.foreach(Iterator.scala:893)
      at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
      at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
      at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
      at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
      at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
      at com.trueaccord.scalapb.json.JsonFormat$.fromJson(JsonFormat.scala:87)
      at com.trueaccord.scalapb.json.JsonFormat$.fromJsonString(JsonFormat.scala:24)
      ... 42 elided

Any idea what is going wrong? Why would it expect an array for a protobuffer map? Why does it think the field is repeated when really it is a map?

Any insight welcome, thanks!

**Comment by thesamet** [comment]
This is a bug in ScalaPB-json. Thanks for reporting.

**Comment by thesamet** [comment]
Fixed in scalapb-json4s 0.1.2
