### ISSUE TITLE
NoSuchMethodError on json

### ISSUE THREAD

**Issue by yawnt** [trueaccord/ScalaPB#128]
just by simply using `JsonFormat.toJsonString(msg)` I get

```
java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$FieldDescriptor.getJsonName()Ljava/lang/String;
        at com.trueaccord.scalapb.json.JsonFormat$$anonfun$toJson$1.apply(JsonFormat.scala:32)
        at com.trueaccord.scalapb.json.JsonFormat$$anonfun$toJson$1.apply(JsonFormat.scala:30)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.trueaccord.scalapb.json.JsonFormat$.toJson(JsonFormat.scala:30)
        at com.trueaccord.scalapb.json.JsonFormat$.toJsonString(JsonFormat.scala:18)
```

Any idea why?
Thanks!

**Comment by thesamet** [comment]
getJsonName is introduced in protobuf-java >=3.0.0. Could it be that somehow at runtime you are using an older version? If you can post a minimal project that has this issue I can investigate further.

**Comment by sky4star** [comment]
Hi yawnt and thesamet, 

I got the same exception. In my case, I am using ScalaPB with Spark 1.6, and i find Spark is using an older version 2.5.0
Currently, my workaround is changing getJsonName to getName, but i know this is not a good solution. Maybe i should use protobuf-java directly.
Any suggestion?

Thanks!

**Comment by thesamet** [comment]
How do you deploy your code to Spark? It's important to make sure that your code uses protobuf>3.0.0 and not the old 2.5.0 that comes with Spark. To achieve it, we shade `com.google.protobuf.*` when build our fat jar using sbt assembly. See https://trueaccord.github.io/ScalaPB/sparksql.html

**Comment by sky4star** [comment]
Thanks thesamet. I decided to use protobuf-java finally. But your solution is absolutely workable. Thanks for your response, I leant a lot from it!

**Comment by seregasheypak** [comment]
Hi... is it possible somehow to enable protobuf 2.5.0 support for ScalaPB?

**Comment by thesamet-st** [comment]
@seregasheypak , no it's going to be really challenging to support several incompatible versions of protobuf-java at once. What's the reason you need protobuf 2.5.0 support? If it's in the context of Spark, then a soution is described in https://scalapb.github.io/sparksql.html
